package com.example.demo.model;

public class AddMaterials {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column add_material.am_id
     *
     * @mbg.generated Mon Sep 09 14:55:22 CST 2024
     */
    private Long amId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column add_material.m_id
     *
     * @mbg.generated Mon Sep 09 14:55:22 CST 2024
     */
    private Long mId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column add_material.ad_id
     *
     * @mbg.generated Mon Sep 09 14:55:22 CST 2024
     */
    private Long adId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column add_material.is_delete
     *
     * @mbg.generated Mon Sep 09 14:55:22 CST 2024
     */
    private Boolean isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column add_material.am_id
     *
     * @return the value of add_material.am_id
     *
     * @mbg.generated Mon Sep 09 14:55:22 CST 2024
     */
    public Long getAmId() {
        return amId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column add_material.am_id
     *
     * @param amId the value for add_material.am_id
     *
     * @mbg.generated Mon Sep 09 14:55:22 CST 2024
     */
    public void setAmId(Long amId) {
        this.amId = amId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column add_material.m_id
     *
     * @return the value of add_material.m_id
     *
     * @mbg.generated Mon Sep 09 14:55:22 CST 2024
     */
    public Long getmId() {
        return mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column add_material.m_id
     *
     * @param mId the value for add_material.m_id
     *
     * @mbg.generated Mon Sep 09 14:55:22 CST 2024
     */
    public void setmId(Long mId) {
        this.mId = mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column add_material.ad_id
     *
     * @return the value of add_material.ad_id
     *
     * @mbg.generated Mon Sep 09 14:55:22 CST 2024
     */
    public Long getAdId() {
        return adId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column add_material.ad_id
     *
     * @param adId the value for add_material.ad_id
     *
     * @mbg.generated Mon Sep 09 14:55:22 CST 2024
     */
    public void setAdId(Long adId) {
        this.adId = adId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column add_material.is_delete
     *
     * @return the value of add_material.is_delete
     *
     * @mbg.generated Mon Sep 09 14:55:22 CST 2024
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column add_material.is_delete
     *
     * @param isDelete the value for add_material.is_delete
     *
     * @mbg.generated Mon Sep 09 14:55:22 CST 2024
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }
}