package com.example.demo.Mapper;

import com.example.demo.model.Administrator;
import com.example.demo.model.AdministratorExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface AdministratorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated Fri Sep 20 16:24:29 CST 2024
     */
    long countByExample(AdministratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated Fri Sep 20 16:24:29 CST 2024
     */
    int deleteByExample(AdministratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated Fri Sep 20 16:24:29 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated Fri Sep 20 16:24:29 CST 2024
     */
    int insert(Administrator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated Fri Sep 20 16:24:29 CST 2024
     */
    int insertSelective(Administrator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated Fri Sep 20 16:24:29 CST 2024
     */
    List<Administrator> selectByExample(AdministratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated Fri Sep 20 16:24:29 CST 2024
     */
    Administrator selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated Fri Sep 20 16:24:29 CST 2024
     */
    int updateByExampleSelective(@Param("record") Administrator record, @Param("example") AdministratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated Fri Sep 20 16:24:29 CST 2024
     */
    int updateByExample(@Param("record") Administrator record, @Param("example") AdministratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated Fri Sep 20 16:24:29 CST 2024
     */
    int updateByPrimaryKeySelective(Administrator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated Fri Sep 20 16:24:29 CST 2024
     */
    int updateByPrimaryKey(Administrator record);

    // 自定义部分

    /**
     * 通过用户名查找管理员
     * 用于检查注册时用户名是否已经存在
     */
    Administrator findByUsername(@Param("username") String username);

    /**
     * 通过用户名和密码查找管理员
     * 用于登录验证
     */
    Administrator login(@Param("username") String username, @Param("password") String password);

}