package com.example.demo.Mapper;

import com.example.demo.model.ActivityType;
import com.example.demo.model.ActivityTypeExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface ActivityTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_type
     *
     * @mbg.generated Mon Sep 09 14:55:22 CST 2024
     */
    long countByExample(ActivityTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_type
     *
     * @mbg.generated Mon Sep 09 14:55:22 CST 2024
     */
    int deleteByExample(ActivityTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_type
     *
     * @mbg.generated Mon Sep 09 14:55:22 CST 2024
     */
    int deleteByPrimaryKey(Long atId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_type
     *
     * @mbg.generated Mon Sep 09 14:55:22 CST 2024
     */
    int insert(ActivityType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_type
     *
     * @mbg.generated Mon Sep 09 14:55:22 CST 2024
     */
    int insertSelective(ActivityType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_type
     *
     * @mbg.generated Mon Sep 09 14:55:22 CST 2024
     */
    List<ActivityType> selectByExample(ActivityTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_type
     *
     * @mbg.generated Mon Sep 09 14:55:22 CST 2024
     */
    ActivityType selectByPrimaryKey(Long atId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_type
     *
     * @mbg.generated Mon Sep 09 14:55:22 CST 2024
     */
    int updateByExampleSelective(@Param("record") ActivityType record, @Param("example") ActivityTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_type
     *
     * @mbg.generated Mon Sep 09 14:55:22 CST 2024
     */
    int updateByExample(@Param("record") ActivityType record, @Param("example") ActivityTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_type
     *
     * @mbg.generated Mon Sep 09 14:55:22 CST 2024
     */
    int updateByPrimaryKeySelective(ActivityType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_type
     *
     * @mbg.generated Mon Sep 09 14:55:22 CST 2024
     */
    int updateByPrimaryKey(ActivityType record);
}