package com.example.demo.Mapper;

import com.example.demo.model.ScoreType;
import com.example.demo.model.ScoreTypeExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface ScoreTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_type
     *
     * @mbg.generated Mon Sep 09 14:55:22 CST 2024
     */
    long countByExample(ScoreTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_type
     *
     * @mbg.generated Mon Sep 09 14:55:22 CST 2024
     */
    int deleteByExample(ScoreTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_type
     *
     * @mbg.generated Mon Sep 09 14:55:22 CST 2024
     */
    int deleteByPrimaryKey(Long stId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_type
     *
     * @mbg.generated Mon Sep 09 14:55:22 CST 2024
     */
    int insert(ScoreType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_type
     *
     * @mbg.generated Mon Sep 09 14:55:22 CST 2024
     */
    int insertSelective(ScoreType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_type
     *
     * @mbg.generated Mon Sep 09 14:55:22 CST 2024
     */
    List<ScoreType> selectByExample(ScoreTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_type
     *
     * @mbg.generated Mon Sep 09 14:55:22 CST 2024
     */
    ScoreType selectByPrimaryKey(Long stId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_type
     *
     * @mbg.generated Mon Sep 09 14:55:22 CST 2024
     */
    int updateByExampleSelective(@Param("record") ScoreType record, @Param("example") ScoreTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_type
     *
     * @mbg.generated Mon Sep 09 14:55:22 CST 2024
     */
    int updateByExample(@Param("record") ScoreType record, @Param("example") ScoreTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_type
     *
     * @mbg.generated Mon Sep 09 14:55:22 CST 2024
     */
    int updateByPrimaryKeySelective(ScoreType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_type
     *
     * @mbg.generated Mon Sep 09 14:55:22 CST 2024
     */
    int updateByPrimaryKey(ScoreType record);
}